### PR TITLE
Fixed gambling caused by incorrect marshal, updated assembly version

### PR DESCRIPTION
**Pull request by Akarinnnnn**
Gambling is caused by `[MarshalAs(UnmanagedType.ByValTStr...`
Changed it to `[MarshalAs(UnmanagedType.ByValArray...` and added a property to operate it

### CODE REVIEW

**Comment by Akarinnnnn** [comment]
This .NET Core project will also pack a Nuget package while building

**Comment by rlabrecque** [comment]
Hey, thanks, I'll get to this soon! Definitely a good improvement, though I'll probably redo the marshalling part in Steamworks.NET-CodeGen to automatically do stub out the string <-> byte[] conversion code

**Comment by rlabrecque** [comment]
Could you check this out?

https://github.com/rlabrecque/Steamworks.NET/pull/347

We can't use Span because Unity doesn't support it yet. :(

Maybe #if Unity use this, otherwise use Span?

**Comment by Akarinnnnn** [comment]
> Could you check this out?
> #347
> We can't use Span because Unity doesn't support it yet. :(
> Maybe #if Unity use this, otherwise use Span?

We don't need Span<T> now.
By the way
``` diff
--- a/Plugins/Steamworks.NET/InteropHelp.cs                                                                             
+++ b/Plugins/Steamworks.NET/InteropHelp.cs
@@ -74,7 +74,7 @@ namespace Steamworks {

                public static void StringToByteArrayUTF8(string str, byte[] outArrayBuffer, int outArrayBufferSize)
                {
-                       outArrayBuffer = new byte[outArrayBufferSize];
+                       //outArrayBuffer = new byte[outArrayBufferSize];
                        int length = Encoding.UTF8.GetBytes(str, 0, str.Length, outArrayBuffer, 0);
                        outArrayBuffer[length] = 0;
                }
```
`outArrayBuffer` should not be overriden, or our data won't written to correct buffer.

**Comment by rlabrecque** [comment]
I'm worried about two things: The `\0`, and also StringToByteArrayUTF8 writing more than outArrayBufferSize maybe?

**Comment by Akarinnnnn** [comment]
> I'm worried about two things: The \0, and also StringToByteArrayUTF8 writing more than outArrayBufferSize maybe?

```csharp
> string str = "简体中文";
> str.Length
4
> byte[] buffer = new byte[20];
> buffer
byte[20] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
> StringToByteArrayUTF8(str, buffer, 0);
> buffer
byte[20] { 231, 174, 128, 228, 189, 147, 228, 184, 173, 230, 150, 135, 0, 0, 0, 0, 0, 0, 0, 0 }
> buffer[13] = 231;
> buffer[14] = 174;
> buffer[15] = 128;
> ByteArrayToStringUTF8(buffer)
"简体中文"
> 
```
`\0` is there, nothing to worry about.
```csharp
> byte[] buff2 = new byte[1];
> StringToByteArrayUTF8(str, buff2, 0);
System.ArgumentException: 输出字节缓冲区太小，无法包含编码后的数据，编码“Unicode (UTF-8)”的操作回退“System.Text.EncoderReplacementFallback”。
参数名: bytes
  + System.Text.Encoding.ThrowBytesOverflow()
  + System.Text.Encoding.ThrowBytesOverflow(System.Text.EncoderNLS, bool)
  + System.Text.UTF8Encoding.GetBytes(System.Char*, int, System.Byte*, int, System.Text.EncoderNLS)
  + System.Text.UTF8Encoding.GetBytes(string, int, int, byte[], int)
  + Submission#0.StringToByteArrayUTF8(string, byte[], int)
```
This shown if you try to write to a buffer that not large enough, `UTF8Encoding.GetBytes` will throw an `System.ArgumentException`.

**Comment by yaakov-h** [comment]
You definitely need to write `\0` or otherwise zero out the array when writing, otherwise you can land up with garbage from previous values.

```csharp
> var buffer = new byte[20];
> var str = "12345";
> Encoding.UTF8.GetBytes(str, 0, str.Length, buffer, 0);
> Encoding.UTF8.GetString(buffer)
"12345\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
> str = "543";
> Encoding.UTF8.GetBytes(str, 0, str.Length, buffer, 0);
> Encoding.UTF8.GetString(buffer)
"54345\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
>
```

**Comment by Akarinnnnn** [comment]
> You definitely need to write \0 or otherwise zero out the array when writing, otherwise you can land up with garbage from previous values.
> > var buffer = new byte[20];
> > var str = "12345";
> > Encoding.UTF8.GetBytes(str, 0, str.Length, buffer, 0);
> > Encoding.UTF8.GetString(buffer)
> "12345\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
> > str = "543";
> > Encoding.UTF8.GetBytes(str, 0, str.Length, buffer, 0);
> > Encoding.UTF8.GetString(buffer)
> "54345\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
> >

Sloved, see [My work](https://github.com/Akarinnnnn/Steamworks.NET/blob/u8str-b/Plugins/Steamworks.NET/InteropHelp.cs).

**Comment by rlabrecque** [comment]
Yeah I think that's looking better.

```
		public static void StringToByteArrayUTF8(string str, byte[] outArrayBuffer, int outArrayBufferSize)
		{
			int length = Encoding.UTF8.GetBytes(str, 0, str.Length, outArrayBuffer, 0);
#if NETSTANDARD2_1
			System.Index index = length >= outArrayBuffer.Length ? ^1 : length;
#else
			int index = length >= outArrayBuffer.Length ? outArrayBuffer.Length - 1 : length;
#endif
			outArrayBuffer[index] = 0;
		}
```

@yaakov-h ? ^

**Pull request closed without merging**
