### PR TITLE
Added STEAMWORKS_NET define

### LINKED ISSUE #464: SteamUnifiedMessage.meta
> Couldn't delete Packages/com.rlabrecque.steamworks.net/Runtime/types/SteamUnifiedMessages.meta because it's in an immutable folder.

You need to remove the Packages/com.rlabrecque.steamworks.net/Runtime/types/SteamUnifiedMessages.meta file or PackageMannager will throw warnings for user's installing the package

### PR DESCRIPTION
**Pull request by JamesMcGhee**
Added a script define that will be added to the Player Script Define list if Steamworks.NET is installed.
This has been requested by other parties that integrate with Steamworks.NET so they can perform checks to insure Steamworks.NET is present before compiling there own code that is dependent on it.

I also removed an unused meta file

resolves #464

### CODE REVIEW

**Comment by JamesMcGhee** [comment]
For note on this 

I am working with Mirror, MLAPI and FishNetworking to help make there respective "Steam Transports" compatable with Steawmworks.NET as it is when installed from Package Manager or otherwise without modification.

One of the things they need to insure errors are not thrown on install of there packages is some way to reliably know when Steamworks.NET is installed or not.

The way Unity's tools and other assets do that is via a script define that the asset/tool adds to Unity's Player settings when the tool is loaded by the editor. So I have done the same here, when Steamworks.NET is loaded by the editor in the same action it would normally use to check for the missing steam_appid.txt it calls another action that will check for the absense of STAMWORKS_NET and if found will add it to the current script defines.

As a result other tools can now create code that is conditional on Steamworks.NET being installed via simple checks

```csharp
#if STEAMWORKS_NET
 // Is installed so dependent code goes here
#else
 // Is not installed so do nothing or notify the user of missing Steamworks.NET and provide install instrucitons
#endif
```

**Comment by JamesMcGhee** [comment]
I have added a samples install that can be added optionally by the user and contains an example of initalizing the Steam API

image

Note I am not using the old SteamManager as I had several issues with some of the assumptions it was making and doing. This new sample has the following key features

1. We clearly and loudly identify this as a sample. This is to try and combat the very bad habit of people taking sample code and just deploying it to production. The sample behaviours flag them selves as obsolete with instructions that they are examples only.
2. We do not assume the user is using Do Not Destroy On Load. There are various architectures where that is problematic
3. We check for Steam is Running, a common issue we see from our clients is trying to test with Steam shut down
4. We split the behaviour in 2, 1 checks if it needs to create the behaviour or if its already there, if it needs to create it it will create it. The other does nothing but opearte the API e.g. initalize, update and shutdown. This means a user could add the ExampleSteamworksBehaviour to every scene even scenes the load multiple times and there would be no issues. The old model of checking for and revoming the object if duplicated caused several issues for users in the past.
5. We added more comments and debug info, a user should be able to read the 2 script files much like a tutorial and the resulting debug logs should tell the user whats going on at each step e.g. if there is an error why and how to fix it and if all worked what the result is e.g. intialized as X user and Y app ID ... since its easy enough for users to forget to update the App ID in steam_appid.txt and thus initalize as 480 but think they are initalized as there own app

**Comment by JamesMcGhee** [comment]
We can add additional examples and tests later as required

**Comment by rlabrecque** [comment]
Can you split out the sample into a separate change, and clean up the formatting on the STEAMWORKS_NET define? Then I'll merge this in 👍

**Comment by JamesMcGhee** [comment]
Me and git rarely get along but I will give it a go

What formatting do you need cleaned up?

**Comment by JamesMcGhee** [comment]
Got to say I hate how combersom Git is compared to how easy TFS was with regards to branches and all ... I guess the best thing is to just trash all this work and redo it on a clean fork ... for some strange reason it thinks there should be only 1 forke off the master?

Im sure its just me and git not seeing eye to eye but it seems so much less friendly than basicly everyother source control and management system out there :)

**Comment by JamesMcGhee** [comment]
Have a look at that

Didn't change anything with the defaine, the method I used is the same used in other assets let me know what you would like changed about it.

I just removed the sample can revist that later I suppose.

**Comment by redwyre** [comment]
I'm not sure this is a good idea, as Unity has support for doing this: https://docs.unity3d.com/2020.1/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html#define-symbols

**Comment by JamesMcGhee** [comment]
The method used is the same used by several other assets

How exsactly its done really doesn't matter to me the request came in from other asset developers to define so they can detect when Steamworks.NET is installed

We do a fair bit of work with other asset devs including MLAPI / NetCode for GameObjects team to try and make better use of Steamworks.NET with there various integrations Steam Networking transports for various networking APIs mostly

**Comment by JamesMcGhee** [comment]
I have done further testing and around the concept referenced by @redwyre 

The result is no
The Assembly Definition Define Symbols doesn't work as expected or I am not understanding its use

From what I understand you should be able to conditionally defien so for example we should be able to say 
if Unity > 1.0.0 then define STEAMWORKS_NET
image

Then we should be able to test for STEAMWORKS_NET as we would with any defien

```csharp
#if STEAMWORKS_NET
        Debug.Log("Steamworks is defined");
#else
        Debug.Log("Steamworks is not defined");
#endif
```

However that is not the case, I tested several options including examples they gave and did not get the desired results. This was using Unity 2019.4.34f1

Thus it is my openion that there is no harm in using the traditional scripting method
The method presented in the Script Define is either not well documented or not working as I world expect so I would expect others to have similar issues with it

For note I gave a try to various Version Define settings and did not have any luck

**Comment by JamesMcGhee** [comment]
@rlabrecque 
Do you have any outstanding requirements to get this one implamented?

**Comment by rlabrecque** [comment]
I cleaned it up and merged it via #484 👍

I wasn't able to merge this one outright because of:
image

**Comment by JamesMcGhee** [comment]
@rlabrecque 

I did a thing
https://github.com/heathen-engineering/SteamworksFoundation

In particular I split out the "foundation" of our Unity Asset Steamworks Complete and published it on Git

I also set up the package manager for it and the install steps such that if a user installed it via Git ... it would check for dependencies and install them as required if the user wants ... and it gives the user a button under the Help menu that can update it, System Core (one of our other dependencies) or Steamworks.NET

I'm still playing with it but so far it works out being a 1 button press to do what was once a major pain in the arse

This would also provide your users a free way of seeing Steamworks.NET working if your/they wanted ... our Steamworks Foundation includes 3 sample scenes

1. Quick Start ... just initalizes the API
2. User Data ... shows the use of users data (avatar, name, etc.)
3. Stats and Achievements ... shows the use of stats and achievements

I have the read me on that pointing back at you ... let me know if you see something that needs changing regarding your Steamworks.NET or anything else for that matter

**Comment by msklywenn** [comment]
Is this just the opposite of DISABLESTEAMWORKS or is there extra meaning?

**Comment by rlabrecque** [comment]
They are distinctly separate.

`STEAMWORKS_NET` is now [always?] defined project wide if the Steamworks package is included at all.

It should only probably only be used by other packages that want to switch behavior if Steamworks.NET is available. I.E. Use Unity Input stuff if it's not available, or SteamInput via Steamworks.NET if it is available.

**Comment by JamesMcGhee** [comment]
@msklywenn As @rlabrecque noted they fill 2 different roles

the DISABLESTEAMWORKS tells the script in Steamworks.NET and many 3rd party assets that build on top to not compile if it is defined. It gets defined when the platform is not a supported platform or if you define it your self in the Unity Player Settings Script Defines.

The STEAMWORKS_NET is defined when Steamworks.NET installs and is defined from an editor script ... this can be used by 3rd party tools like Mirror, our own integration, etc. know that Steamworks.NET is installed as so we can compile code that is dependent on it.

So the way I keep it right in my head
DISABLESTEMWORKS = "Please do not include Steam stuff in the build"
STEAMWORKS_NET = "Steamworks.NET is installed in the project"

**Comment by v01pe** [comment]
> I'm not sure this is a good idea, as Unity has support for doing this: https://docs.unity3d.com/2020.1/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html#define-symbols

Agreed, I don't like it when plugins spam the global script defines.

> However this only applies to the code within that assembly so its uselss for our needs here where we want users of this assembly to be able to know if its installed via script define.

To trigger a warning or similar (to suggest installing steamworks.net), you won't need the define – do it a manner suggested above. I don't see any other benefits your users would get from this?

**Comment by v01pe** [comment]
> this can be used by 3rd party tools like Mirror, our own integration, etc. know that Steamworks.NET is installed as so we can compile code that is dependent on it.

For this use case you would do, what @redwyre suggested for the assembly, that implements said code:
Define in Assembly

**Comment by JamesMcGhee** [comment]
If we depended on the Assembly Define model then Mirror or other such 3rd parties would have to install Steamworks.NET in their source just so they could have the reference to the assembly to create the define. That simply isn't going to happen and isn't' the normal approach used by any of them or even used by Unity its self.

Also the above breaks when a user as they are often want to do changes things, creates there own assembly defines or as is commonly done in Mirror land moves the source of say the FizzySteam transport under the root of Mirror such that there is just 1 assembly define for both ... now the method you described is broken unless Mirror had Steamworks.NET as a dependency of it ... which why would it, its not.


No the simpler and already established method with various asset developers including Unity's own community assets is to have such SDKs, APIs or Systems define a global define that indicates they are present. For note our asset doesn't use this approach so for our own asset I only care so far that supporting a script define globally like this means that Mirror and others stop embedding a copy of Steamworks.NET in there own code making a true hell scape of a mess.


All in what I am saying is that while yes it could be done and was for years done without this define at all ... making a global define which is pretty box standard among various asset developers including Unity its self is the simpler and more common approach than expecting each user of an assembly define which for note includes end users not just authors of assets, from creating the define them selves. or worse just embedding the source in there own source which OMFG lets not get back into that horrible habit.

As for Heathen's own asset ... this doesn't actually apply to us, as we are dependent on Steamworks.NET we check for it being installed via Package Manager in an editor script as a dependency. If that check fails we offer to install Steamwork.NET for the user though Package Manger if it passes all is well and we move on. We do this because of the absolute hell scape caused when people where advised to copy / embed 3rd party code in there own assets ... so for the typical Unity dev that used Steamworks.NET and maybe 3 or 4 other assets that also used Steamworks.NET Unity was making an absolute trash storm of failed and mangled merges due to 3 or 4 deep copies of the code :D that accounted for well more than half of all support we ever saw.

But anyway ... including 3rd party assemblies that might be needed by add-ons in an assembly define so one can create a version reference is is not how Mirror, FishNetworking, NetCode for GameObjects, or really any other asset I have ever worked with or supported does it. They all expect a script define that indicates said feature is present as that is the standard Unity created with its own "conditional compilation" documentation and approach. Where that is not present they either do not support it, leave the user to figure it out on there own, or and this is the worst of all, embed a copy of it in there own code.

**Pull request closed without merging**
